name: Deploy Golang App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-host

    steps:
    - name: Start WireGuard VPN
      run: sudo wg-quick up /home/ubuntu/testing.conf

    - name: Deploy Application
      run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /home/ubuntu/go-test/manual/go-talkjs; git pull; make dep; make build; sudo supervisorctl restart all"

    - name: Stop WireGuard VPN
      run: sudo wg-quick down /home/ubuntu/testing.conf