name: Deploy Golang App

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted
    environment: staging

    steps:
    - name: Start WireGuard VPN
      run: sudo wg-quick up /home/ubuntu/testing.conf

    - name: Deploy Application
      run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /home/ubuntu/go-test/manual/go-talkjs; git pull; go mod tidy; go mod vendor; set GOOS=linux && set GOARCH=amd64 && go build -o bin/talkjs main.go; sudo supervisorctl restart all"

    - name: Stop WireGuard VPN
      run: sudo wg-quick down /home/ubuntu/testing.conf