name: Deploy GO App Production

on:
  push:
    tags:
      - p-v*

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Start WireGuard VPN
      run: sudo wg-quick up /home/ubuntu/testing-prod.conf

    - name: Deploy Application
      if: success() || failure()
      run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /home/ubuntu/go-test/go-talkjs; git pull; export GOPATH=$HOME/go-test; export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin; make dep; make build; sudo supervisorctl restart all"
      
    - name: Stop WireGuard VPN
      if: success() || failure()
      run: sudo wg-quick down /home/ubuntu/testing-prod.conf
